/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BuilderRouteImport } from './routes/builder'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as ResumeTemplateRouteImport } from './routes/resume/template'
import { Route as ProjectsIdRouteImport } from './routes/projects/$id'
import { Route as PortfolioNewRouteImport } from './routes/portfolio/new'
import { Route as PortfolioIdRouteImport } from './routes/portfolio/$id'

const BuilderRoute = BuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeTemplateRoute = ResumeTemplateRouteImport.update({
  id: '/resume/template',
  path: '/resume/template',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdRoute = ProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioNewRoute = PortfolioNewRouteImport.update({
  id: '/portfolio/new',
  path: '/portfolio/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioIdRoute = PortfolioIdRouteImport.update({
  id: '/portfolio/$id',
  path: '/portfolio/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/builder': typeof BuilderRoute
  '/portfolio/$id': typeof PortfolioIdRoute
  '/portfolio/new': typeof PortfolioNewRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/resume/template': typeof ResumeTemplateRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/builder': typeof BuilderRoute
  '/portfolio/$id': typeof PortfolioIdRoute
  '/portfolio/new': typeof PortfolioNewRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/resume/template': typeof ResumeTemplateRoute
  '/projects': typeof ProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/builder': typeof BuilderRoute
  '/portfolio/$id': typeof PortfolioIdRoute
  '/portfolio/new': typeof PortfolioNewRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/resume/template': typeof ResumeTemplateRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/builder'
    | '/portfolio/$id'
    | '/portfolio/new'
    | '/projects/$id'
    | '/resume/template'
    | '/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/builder'
    | '/portfolio/$id'
    | '/portfolio/new'
    | '/projects/$id'
    | '/resume/template'
    | '/projects'
  id:
    | '__root__'
    | '/'
    | '/builder'
    | '/portfolio/$id'
    | '/portfolio/new'
    | '/projects/$id'
    | '/resume/template'
    | '/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuilderRoute: typeof BuilderRoute
  PortfolioIdRoute: typeof PortfolioIdRoute
  PortfolioNewRoute: typeof PortfolioNewRoute
  ProjectsIdRoute: typeof ProjectsIdRoute
  ResumeTemplateRoute: typeof ResumeTemplateRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/builder': {
      id: '/builder'
      path: '/builder'
      fullPath: '/builder'
      preLoaderRoute: typeof BuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume/template': {
      id: '/resume/template'
      path: '/resume/template'
      fullPath: '/resume/template'
      preLoaderRoute: typeof ResumeTemplateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id': {
      id: '/projects/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof ProjectsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/new': {
      id: '/portfolio/new'
      path: '/portfolio/new'
      fullPath: '/portfolio/new'
      preLoaderRoute: typeof PortfolioNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/$id': {
      id: '/portfolio/$id'
      path: '/portfolio/$id'
      fullPath: '/portfolio/$id'
      preLoaderRoute: typeof PortfolioIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuilderRoute: BuilderRoute,
  PortfolioIdRoute: PortfolioIdRoute,
  PortfolioNewRoute: PortfolioNewRoute,
  ProjectsIdRoute: ProjectsIdRoute,
  ResumeTemplateRoute: ResumeTemplateRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
