/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as ResumeTemplateRouteImport } from './routes/resume/template'
import { Route as ResumeAiInterviewRouteImport } from './routes/resume/ai-interview'
import { Route as ProjectsIdRouteImport } from './routes/projects/$id'
import { Route as BlogWriteRouteImport } from './routes/blog/write'
import { Route as BlogIdRouteImport } from './routes/blog/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeTemplateRoute = ResumeTemplateRouteImport.update({
  id: '/resume/template',
  path: '/resume/template',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeAiInterviewRoute = ResumeAiInterviewRouteImport.update({
  id: '/resume/ai-interview',
  path: '/resume/ai-interview',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdRoute = ProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogWriteRoute = BlogWriteRouteImport.update({
  id: '/blog/write',
  path: '/blog/write',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIdRoute = BlogIdRouteImport.update({
  id: '/blog/$id',
  path: '/blog/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog/$id': typeof BlogIdRoute
  '/blog/write': typeof BlogWriteRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/resume/ai-interview': typeof ResumeAiInterviewRoute
  '/resume/template': typeof ResumeTemplateRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog/$id': typeof BlogIdRoute
  '/blog/write': typeof BlogWriteRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/resume/ai-interview': typeof ResumeAiInterviewRoute
  '/resume/template': typeof ResumeTemplateRoute
  '/projects': typeof ProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog/$id': typeof BlogIdRoute
  '/blog/write': typeof BlogWriteRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/resume/ai-interview': typeof ResumeAiInterviewRoute
  '/resume/template': typeof ResumeTemplateRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog/$id'
    | '/blog/write'
    | '/projects/$id'
    | '/resume/ai-interview'
    | '/resume/template'
    | '/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog/$id'
    | '/blog/write'
    | '/projects/$id'
    | '/resume/ai-interview'
    | '/resume/template'
    | '/projects'
  id:
    | '__root__'
    | '/'
    | '/blog/$id'
    | '/blog/write'
    | '/projects/$id'
    | '/resume/ai-interview'
    | '/resume/template'
    | '/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogIdRoute: typeof BlogIdRoute
  BlogWriteRoute: typeof BlogWriteRoute
  ProjectsIdRoute: typeof ProjectsIdRoute
  ResumeAiInterviewRoute: typeof ResumeAiInterviewRoute
  ResumeTemplateRoute: typeof ResumeTemplateRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume/template': {
      id: '/resume/template'
      path: '/resume/template'
      fullPath: '/resume/template'
      preLoaderRoute: typeof ResumeTemplateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume/ai-interview': {
      id: '/resume/ai-interview'
      path: '/resume/ai-interview'
      fullPath: '/resume/ai-interview'
      preLoaderRoute: typeof ResumeAiInterviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id': {
      id: '/projects/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof ProjectsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/write': {
      id: '/blog/write'
      path: '/blog/write'
      fullPath: '/blog/write'
      preLoaderRoute: typeof BlogWriteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$id': {
      id: '/blog/$id'
      path: '/blog/$id'
      fullPath: '/blog/$id'
      preLoaderRoute: typeof BlogIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogIdRoute: BlogIdRoute,
  BlogWriteRoute: BlogWriteRoute,
  ProjectsIdRoute: ProjectsIdRoute,
  ResumeAiInterviewRoute: ResumeAiInterviewRoute,
  ResumeTemplateRoute: ResumeTemplateRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
