/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogWriteRouteImport } from './routes/blog/write'
import { Route as BlogIdRouteImport } from './routes/blog/$id'

const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogWriteRoute = BlogWriteRouteImport.update({
  id: '/blog/write',
  path: '/blog/write',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIdRoute = BlogIdRouteImport.update({
  id: '/blog/$id',
  path: '/blog/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/blog/$id': typeof BlogIdRoute
  '/blog/write': typeof BlogWriteRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/blog/$id': typeof BlogIdRoute
  '/blog/write': typeof BlogWriteRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/blog/$id': typeof BlogIdRoute
  '/blog/write': typeof BlogWriteRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/blog/$id' | '/blog/write' | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to: '/blog/$id' | '/blog/write' | '/blog'
  id: '__root__' | '/blog/$id' | '/blog/write' | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  BlogIdRoute: typeof BlogIdRoute
  BlogWriteRoute: typeof BlogWriteRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/write': {
      id: '/blog/write'
      path: '/blog/write'
      fullPath: '/blog/write'
      preLoaderRoute: typeof BlogWriteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$id': {
      id: '/blog/$id'
      path: '/blog/$id'
      fullPath: '/blog/$id'
      preLoaderRoute: typeof BlogIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  BlogIdRoute: BlogIdRoute,
  BlogWriteRoute: BlogWriteRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
