/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResumeToPortfolioRouteImport } from './routes/resume-to-portfolio'
import { Route as ResumeRouteImport } from './routes/resume'
import { Route as ReasoningMockRouteImport } from './routes/reasoning-mock'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as PhotofolioRouteImport } from './routes/photofolio'
import { Route as InterviewRouteImport } from './routes/interview'
import { Route as ClassicRouteImport } from './routes/classic'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PhotofolioIndexRouteImport } from './routes/photofolio.index'
import { Route as PolandFrontendRouteImport } from './routes/poland/frontend'
import { Route as PolandBackendRouteImport } from './routes/poland/backend'
import { Route as PhotofolioProjectIdRouteImport } from './routes/photofolio.$projectId'
import { Route as GermanyBackendRouteImport } from './routes/germany/backend'
import { Route as PhotofolioProjectIdSettingsRouteImport } from './routes/photofolio.$projectId_.settings'

const ResumeToPortfolioRoute = ResumeToPortfolioRouteImport.update({
  id: '/resume-to-portfolio',
  path: '/resume-to-portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeRoute = ResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const ReasoningMockRoute = ReasoningMockRouteImport.update({
  id: '/reasoning-mock',
  path: '/reasoning-mock',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotofolioRoute = PhotofolioRouteImport.update({
  id: '/photofolio',
  path: '/photofolio',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewRoute = InterviewRouteImport.update({
  id: '/interview',
  path: '/interview',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassicRoute = ClassicRouteImport.update({
  id: '/classic',
  path: '/classic',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotofolioIndexRoute = PhotofolioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PhotofolioRoute,
} as any)
const PolandFrontendRoute = PolandFrontendRouteImport.update({
  id: '/poland/frontend',
  path: '/poland/frontend',
  getParentRoute: () => rootRouteImport,
} as any)
const PolandBackendRoute = PolandBackendRouteImport.update({
  id: '/poland/backend',
  path: '/poland/backend',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotofolioProjectIdRoute = PhotofolioProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => PhotofolioRoute,
} as any)
const GermanyBackendRoute = GermanyBackendRouteImport.update({
  id: '/germany/backend',
  path: '/germany/backend',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotofolioProjectIdSettingsRoute =
  PhotofolioProjectIdSettingsRouteImport.update({
    id: '/$projectId_/settings',
    path: '/$projectId/settings',
    getParentRoute: () => PhotofolioRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/classic': typeof ClassicRoute
  '/interview': typeof InterviewRoute
  '/photofolio': typeof PhotofolioRouteWithChildren
  '/portfolio': typeof PortfolioRoute
  '/reasoning-mock': typeof ReasoningMockRoute
  '/resume': typeof ResumeRoute
  '/resume-to-portfolio': typeof ResumeToPortfolioRoute
  '/germany/backend': typeof GermanyBackendRoute
  '/photofolio/$projectId': typeof PhotofolioProjectIdRoute
  '/poland/backend': typeof PolandBackendRoute
  '/poland/frontend': typeof PolandFrontendRoute
  '/photofolio/': typeof PhotofolioIndexRoute
  '/photofolio/$projectId/settings': typeof PhotofolioProjectIdSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/classic': typeof ClassicRoute
  '/interview': typeof InterviewRoute
  '/portfolio': typeof PortfolioRoute
  '/reasoning-mock': typeof ReasoningMockRoute
  '/resume': typeof ResumeRoute
  '/resume-to-portfolio': typeof ResumeToPortfolioRoute
  '/germany/backend': typeof GermanyBackendRoute
  '/photofolio/$projectId': typeof PhotofolioProjectIdRoute
  '/poland/backend': typeof PolandBackendRoute
  '/poland/frontend': typeof PolandFrontendRoute
  '/photofolio': typeof PhotofolioIndexRoute
  '/photofolio/$projectId/settings': typeof PhotofolioProjectIdSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/classic': typeof ClassicRoute
  '/interview': typeof InterviewRoute
  '/photofolio': typeof PhotofolioRouteWithChildren
  '/portfolio': typeof PortfolioRoute
  '/reasoning-mock': typeof ReasoningMockRoute
  '/resume': typeof ResumeRoute
  '/resume-to-portfolio': typeof ResumeToPortfolioRoute
  '/germany/backend': typeof GermanyBackendRoute
  '/photofolio/$projectId': typeof PhotofolioProjectIdRoute
  '/poland/backend': typeof PolandBackendRoute
  '/poland/frontend': typeof PolandFrontendRoute
  '/photofolio/': typeof PhotofolioIndexRoute
  '/photofolio/$projectId_/settings': typeof PhotofolioProjectIdSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/classic'
    | '/interview'
    | '/photofolio'
    | '/portfolio'
    | '/reasoning-mock'
    | '/resume'
    | '/resume-to-portfolio'
    | '/germany/backend'
    | '/photofolio/$projectId'
    | '/poland/backend'
    | '/poland/frontend'
    | '/photofolio/'
    | '/photofolio/$projectId/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/classic'
    | '/interview'
    | '/portfolio'
    | '/reasoning-mock'
    | '/resume'
    | '/resume-to-portfolio'
    | '/germany/backend'
    | '/photofolio/$projectId'
    | '/poland/backend'
    | '/poland/frontend'
    | '/photofolio'
    | '/photofolio/$projectId/settings'
  id:
    | '__root__'
    | '/'
    | '/classic'
    | '/interview'
    | '/photofolio'
    | '/portfolio'
    | '/reasoning-mock'
    | '/resume'
    | '/resume-to-portfolio'
    | '/germany/backend'
    | '/photofolio/$projectId'
    | '/poland/backend'
    | '/poland/frontend'
    | '/photofolio/'
    | '/photofolio/$projectId_/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClassicRoute: typeof ClassicRoute
  InterviewRoute: typeof InterviewRoute
  PhotofolioRoute: typeof PhotofolioRouteWithChildren
  PortfolioRoute: typeof PortfolioRoute
  ReasoningMockRoute: typeof ReasoningMockRoute
  ResumeRoute: typeof ResumeRoute
  ResumeToPortfolioRoute: typeof ResumeToPortfolioRoute
  GermanyBackendRoute: typeof GermanyBackendRoute
  PolandBackendRoute: typeof PolandBackendRoute
  PolandFrontendRoute: typeof PolandFrontendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/resume-to-portfolio': {
      id: '/resume-to-portfolio'
      path: '/resume-to-portfolio'
      fullPath: '/resume-to-portfolio'
      preLoaderRoute: typeof ResumeToPortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume': {
      id: '/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof ResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reasoning-mock': {
      id: '/reasoning-mock'
      path: '/reasoning-mock'
      fullPath: '/reasoning-mock'
      preLoaderRoute: typeof ReasoningMockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photofolio': {
      id: '/photofolio'
      path: '/photofolio'
      fullPath: '/photofolio'
      preLoaderRoute: typeof PhotofolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview': {
      id: '/interview'
      path: '/interview'
      fullPath: '/interview'
      preLoaderRoute: typeof InterviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classic': {
      id: '/classic'
      path: '/classic'
      fullPath: '/classic'
      preLoaderRoute: typeof ClassicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photofolio/': {
      id: '/photofolio/'
      path: '/'
      fullPath: '/photofolio/'
      preLoaderRoute: typeof PhotofolioIndexRouteImport
      parentRoute: typeof PhotofolioRoute
    }
    '/poland/frontend': {
      id: '/poland/frontend'
      path: '/poland/frontend'
      fullPath: '/poland/frontend'
      preLoaderRoute: typeof PolandFrontendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poland/backend': {
      id: '/poland/backend'
      path: '/poland/backend'
      fullPath: '/poland/backend'
      preLoaderRoute: typeof PolandBackendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photofolio/$projectId': {
      id: '/photofolio/$projectId'
      path: '/$projectId'
      fullPath: '/photofolio/$projectId'
      preLoaderRoute: typeof PhotofolioProjectIdRouteImport
      parentRoute: typeof PhotofolioRoute
    }
    '/germany/backend': {
      id: '/germany/backend'
      path: '/germany/backend'
      fullPath: '/germany/backend'
      preLoaderRoute: typeof GermanyBackendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photofolio/$projectId_/settings': {
      id: '/photofolio/$projectId_/settings'
      path: '/$projectId/settings'
      fullPath: '/photofolio/$projectId/settings'
      preLoaderRoute: typeof PhotofolioProjectIdSettingsRouteImport
      parentRoute: typeof PhotofolioRoute
    }
  }
}

interface PhotofolioRouteChildren {
  PhotofolioProjectIdRoute: typeof PhotofolioProjectIdRoute
  PhotofolioIndexRoute: typeof PhotofolioIndexRoute
  PhotofolioProjectIdSettingsRoute: typeof PhotofolioProjectIdSettingsRoute
}

const PhotofolioRouteChildren: PhotofolioRouteChildren = {
  PhotofolioProjectIdRoute: PhotofolioProjectIdRoute,
  PhotofolioIndexRoute: PhotofolioIndexRoute,
  PhotofolioProjectIdSettingsRoute: PhotofolioProjectIdSettingsRoute,
}

const PhotofolioRouteWithChildren = PhotofolioRoute._addFileChildren(
  PhotofolioRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClassicRoute: ClassicRoute,
  InterviewRoute: InterviewRoute,
  PhotofolioRoute: PhotofolioRouteWithChildren,
  PortfolioRoute: PortfolioRoute,
  ReasoningMockRoute: ReasoningMockRoute,
  ResumeRoute: ResumeRoute,
  ResumeToPortfolioRoute: ResumeToPortfolioRoute,
  GermanyBackendRoute: GermanyBackendRoute,
  PolandBackendRoute: PolandBackendRoute,
  PolandFrontendRoute: PolandFrontendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
