/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ClassicRouteImport } from './routes/classic'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PolandFrontendRouteImport } from './routes/poland/frontend'
import { Route as PolandBackendRouteImport } from './routes/poland/backend'
import { Route as GermanyBackendRouteImport } from './routes/germany/backend'

const ClassicRoute = ClassicRouteImport.update({
  id: '/classic',
  path: '/classic',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PolandFrontendRoute = PolandFrontendRouteImport.update({
  id: '/poland/frontend',
  path: '/poland/frontend',
  getParentRoute: () => rootRouteImport,
} as any)
const PolandBackendRoute = PolandBackendRouteImport.update({
  id: '/poland/backend',
  path: '/poland/backend',
  getParentRoute: () => rootRouteImport,
} as any)
const GermanyBackendRoute = GermanyBackendRouteImport.update({
  id: '/germany/backend',
  path: '/germany/backend',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/classic': typeof ClassicRoute
  '/germany/backend': typeof GermanyBackendRoute
  '/poland/backend': typeof PolandBackendRoute
  '/poland/frontend': typeof PolandFrontendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/classic': typeof ClassicRoute
  '/germany/backend': typeof GermanyBackendRoute
  '/poland/backend': typeof PolandBackendRoute
  '/poland/frontend': typeof PolandFrontendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/classic': typeof ClassicRoute
  '/germany/backend': typeof GermanyBackendRoute
  '/poland/backend': typeof PolandBackendRoute
  '/poland/frontend': typeof PolandFrontendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/classic'
    | '/germany/backend'
    | '/poland/backend'
    | '/poland/frontend'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/classic'
    | '/germany/backend'
    | '/poland/backend'
    | '/poland/frontend'
  id:
    | '__root__'
    | '/'
    | '/classic'
    | '/germany/backend'
    | '/poland/backend'
    | '/poland/frontend'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClassicRoute: typeof ClassicRoute
  GermanyBackendRoute: typeof GermanyBackendRoute
  PolandBackendRoute: typeof PolandBackendRoute
  PolandFrontendRoute: typeof PolandFrontendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/classic': {
      id: '/classic'
      path: '/classic'
      fullPath: '/classic'
      preLoaderRoute: typeof ClassicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poland/frontend': {
      id: '/poland/frontend'
      path: '/poland/frontend'
      fullPath: '/poland/frontend'
      preLoaderRoute: typeof PolandFrontendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poland/backend': {
      id: '/poland/backend'
      path: '/poland/backend'
      fullPath: '/poland/backend'
      preLoaderRoute: typeof PolandBackendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/germany/backend': {
      id: '/germany/backend'
      path: '/germany/backend'
      fullPath: '/germany/backend'
      preLoaderRoute: typeof GermanyBackendRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClassicRoute: ClassicRoute,
  GermanyBackendRoute: GermanyBackendRoute,
  PolandBackendRoute: PolandBackendRoute,
  PolandFrontendRoute: PolandFrontendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
