/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IPrepareRouteImport } from './routes/i-prepare'
import { Route as IndexRouteImport } from './routes/index'

const IPrepareRoute = IPrepareRouteImport.update({
  id: '/i-prepare',
  path: '/i-prepare',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/i-prepare': typeof IPrepareRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/i-prepare': typeof IPrepareRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/i-prepare': typeof IPrepareRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/i-prepare'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/i-prepare'
  id: '__root__' | '/' | '/i-prepare'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IPrepareRoute: typeof IPrepareRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/i-prepare': {
      id: '/i-prepare'
      path: '/i-prepare'
      fullPath: '/i-prepare'
      preLoaderRoute: typeof IPrepareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IPrepareRoute: IPrepareRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
